# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Scalar-Util-Clone
version:      0.01
version_from: lib/Scalar/Util/Clone.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    IO::Handle:                    0
    Scalar::Util:                  1.01
    Test::More:                    0
    Tie::Hash:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
